# 基础配置
# 每行最大长度，适合中英文混排的博客写作
printWidth: 100
# 缩进空格数，统一为 2
tabWidth: 4
# 使用空格而不是 tab
useTabs: false
# 语句末尾加分号（适用于 JS/TS）
semi: true
# 使用单引号（适用于 JS/TS/HTML）
singleQuote: true
# 对象属性仅在必要时加引号
quoteProps: 'as-needed'
# 尾逗号风格，推荐 es5（数组、对象、函数参数）
trailingComma: 'es5'
# JSX 中使用单引号
jsxSingleQuote: true
endOfLine: 'lf' # 统一换行符

# Markdown特定配置
overrides:
  - files: '*.md'
    options:
      # Markdown 中保留原始换行方式
      # proseWrap: preserve
      proseWrap: 'always' # 自动换行保持可读性
      tabWidth: 4 # 兼容代码块缩进
      embeddedLanguageFormatting: 'auto' # 自动格式化代码块

# HTML/JSX配置
# 对象字面量中括号间加空格
bracketSpacing: true
# JSX 标签的反尖括号是否换行（false 表示不换行）
bracketSameLine: false
# 箭头函数参数总是加括号
arrowParens: 'always'
# HTML 空格敏感性设置为忽略（适合嵌套 HTML）
# htmlWhitespaceSensitivity: 'css'
htmlWhitespaceSensitivity: ignore
# 插件集成
# plugins:
#   - "prettier-plugin-tailwindcss"  # 可选TailwindCSS支持
