
# 基础配置
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: "as-needed"
trailingComma: "es5"

# Markdown特定配置
overrides:
  - files: "*.md"
    options:
      proseWrap: "always"  # 自动换行保持可读性
      tabWidth: 4          # 兼容代码块缩进
      embeddedLanguageFormatting: "auto"  # 自动格式化代码块

# HTML/JSX配置
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
htmlWhitespaceSensitivity: "css"

# 插件集成
# plugins:
#   - "prettier-plugin-tailwindcss"  # 可选TailwindCSS支持