# WORKSPACE 文件的作用和用处
#  - 标记项目根目录，可以为空
#  - 可以在里面声明外部依赖（第三方库），例如用 http_archive 下载远程库
#  - 配置项目的全局设置

; load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

; http_archive(
;     name = "googletest",
;     urls = ["https://github.com/google/googletest/archive/release-1.12.1.zip"],
;     strip_prefix = "googletest-release-1.12.1",
;     sha256 = "94c634d499558a01a73f5e24c0b5a15e0a13e832b5d68150c64e7c868bdaeb5b",
; )

; load("@googletest//:bazel/repositories.bzl", "gtest_repositories")

; gtest_repositories()
